version: 2

jobs:
  main:
    docker:
      - image: circleci/python:3.7
    steps:
      # Remove IPv6 entry for localhost in Circle CI containers because it doesn't work anyway.
      - run: sudo cp /etc/hosts /tmp; sudo sed -i '/::1/d' /tmp/hosts; sudo cp /tmp/hosts /etc
      - checkout
      - run: sudo pip install tox codecov
      - run: tox -e coverage,black,flake8,isort
      - run: codecov
  py35:
    docker:
      - image: circleci/python:3.5
    steps:
      # Remove IPv6 entry for localhost in Circle CI containers because it doesn't work anyway.
      - run: sudo cp /etc/hosts /tmp; sudo sed -i '/::1/d' /tmp/hosts; sudo cp /tmp/hosts /etc
      - checkout
      - run: sudo pip install tox
      - run: tox -e py35
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      # Remove IPv6 entry for localhost in Circle CI containers because it doesn't work anyway.
      - run: sudo cp /etc/hosts /tmp; sudo sed -i '/::1/d' /tmp/hosts; sudo cp /tmp/hosts /etc
      - checkout
      - run: sudo pip install tox
      - run: tox -e py36
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      # Remove IPv6 entry for localhost in Circle CI containers because it doesn't work anyway.
      - run: sudo cp /etc/hosts /tmp; sudo sed -i '/::1/d' /tmp/hosts; sudo cp /tmp/hosts /etc
      - checkout
      - run: sudo pip install tox
      - run: tox -e py37

workflows:
  version: 2
  build:
    jobs:
      - main
      - py35:
          requires:
            - main
      - py36:
          requires:
            - main
      - py37:
          requires:
            - main
